### ISSUE TITLE
Documentation: Developer Experience Improvements

### ISSUE THREAD

**Issue by aott33** [joyja/tentacle-plc#4]
Hello @joyja,

Excellent work with this project.

I have a few suggestions for the documentation that I believe would be helpful to get the Tentacle PLC installed and configured.

- Recommended hardware section
   - Perhaps an example of the hardware and OS you have used with the Tentacle PLC. You mentioned some in a [previous issue](https://github.com/joyja/tentacle-plc/issues/3#issuecomment-1120501760)
- Docker configuration examples
   - Specifically, the code-server docker configuration. Is there a way to configuring a user defined password? I needed to explore the docker container config.yaml file to determine the password. See how I determined the code server password **[here]()**
 - Docker container port numbers (I believe this is shown in the docker-compose.yml file, but maybe it would be helpful to have a section describing the default port and urls?). For example:
    - Tentacle PLC
       - ```http://localhost:4000```
    - Tentacle PLC UI
       - ```http://localhost:3000```
    - Code Server
        - ```http://localhost:8080```
- GraphQL example queries and mutations. I am very new to GraphQL so it required a bit of research but that is part of the learning. Something like below would have been helpful to get me started:
   - Query PLC running status:
   ```
   query {
    plc {
        running
        }
    }
   ```
  
   - Mutate restart PLC:
   ```
   mutation {
    startPlc{
        running
    }
   }
   ```

**Comment by joyja** [comment]
All great suggestions. If you have the time @aott33 feel free to fork the repo, make modifications to the markdown files in the docs folder, and submit a pull request. Reminds me that I need to make an issue to create a contributing.md that describes how to run test environments and a local copy of the docs site. If you do end up working on this and have any questions, don't hesitate to reach out. I'll probably make a discord server for contributors so we can real time chat as well.

**Comment by aott33** [comment]
@joyja, I will fork the repo and makes some modifications when I have a chance.

Discord server is a great idea

**Comment by joyja** [comment]
Closed by merging https://github.com/joyja/tentacle-plc/pull/9. Thanks @aott33!
